title       : YeoSJ116's Blog
description : My Personal Blog

author    : YeoSJ116
logo      : /YeoSJ116.github.io/static/img/avatar.png
github    : https://github.com/YeoSJ116
naverBlog : https://blog.naver.com/yeosj116
youtube   : https://www.youtube.com/channel/UCUgrvzrw-JA-uz-5PDX3EZw?view_as=subscriber
contect   : https://YeoSJ116.github.io/#NotYet
about     : Beginner developer (Korean Student)
locale    : "ko_KR" #ICU Locale

url         : "https://YeoSJ116.github.io/"
baseurl     : "https://YeoSJ116.github.io"
repository  : ""

disqus_shortname: 
google_analytics: UA-138900801-1

allowsearch: true
enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]

main_color: "#3f51b5"
sub_color: "#303f9f"

